# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/brightseg',
                'doc_host': 'https://IntegratedPathologyUnit-ICR.github.io',
                'git_url': 'https://github.com/IntegratedPathologyUnit-ICR/brightseg',
                'lib_path': 'brightseg'},
  'syms': {'brightseg.core': {'brightseg.core.foo': ('core.html#foo', 'brightseg/core.py')}}}
